### ISSUE TITLE
Сделать строки таблицы кликабельными

### ISSUE THREAD

**Issue by alxmamaev** [alxmamaev/ESCV#10]
В данный момент в таблице посещений можно просмотреть имена пользователей/кнопок. Хотелось бы, что бы при нажатии на них мы переходили на профиль этого пользователя/комнаты.

**Comment by AZbang** [comment]
Сделано.

**Comment by AZbang** [comment]
Необходимо сделать так: 
```javascript

visit_list = [
   {
      room: {
          name: 'Столовка',
          id: 243
      },
      time: ...,
      date: ....
   }
]
```
И тоже самое для user.

**Comment by AZbang** [comment]
сделано.
