### ISSUE TITLE
Невозможно выбрать дату выше текущей

### ISSUE THREAD

**Issue by alxmamaev** [alxmamaev/ESCV#5]
Когда я перехожу на какую-либо дату, я не могу выбрать дату выше текущей.
![image](https://cloud.githubusercontent.com/assets/17113191/20464218/c4bffb0a-af65-11e6-99b7-8ffa796c26f7.png)

**Comment by AZbang** [comment]
Необходимо, чтобы переменная `date` содержала строку текущей даты. Для начала.

**Comment by alxmamaev** [comment]
Исправлено.
